version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO

  server:
    image: server
    container_name: fastapi_server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
